# Практическая 6

Импорт библиотек

In [1]:
import pandas as pd
import numpy as np

Чтение датасета

In [2]:
df = pd.read_csv("vgsales_12.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,15197,Let's Play Flight Attendant,DS,2010.0,Simulation,Deep Silver,0.02,0.00,0.0,0.00,0.02
1,5292,Mini Ninjas,DS,2009.0,Action,Eidos Interactive,0.17,0.15,0.0,0.04,0.35
2,3119,SingStar Pop Hits,PS2,2007.0,Misc,Sony Computer Entertainment,0.00,0.50,0.0,0.15,0.65
3,13923,Super Army War,GBA,2005.0,Action,Flashpoint Games,0.03,0.01,0.0,0.00,0.04
4,7564,Rocket Power: Zero Gravity Zone,GBA,2003.0,Sports,THQ,0.14,0.05,0.0,0.00,0.20
...,...,...,...,...,...,...,...,...,...,...,...
548,6409,Ultimate NES Remix,3DS,2014.0,Action,Unknown,0.15,0.09,0.0,0.02,0.27
549,11069,Jambo! Safari Animal Rescue,Wii,2009.0,Simulation,Sega,0.07,0.01,0.0,0.01,0.09
550,2311,Tiger Woods PGA Tour 12: The Masters,PS3,2011.0,Sports,Electronic Arts,0.52,0.26,0.0,0.12,0.90
551,8992,Elf: The Movie,GBA,2004.0,Action,Crave Entertainment,0.10,0.04,0.0,0.00,0.15
552,8048,Fear Effect 2: Retro Helix,PS,2001.0,Action,Eidos Interactive,0.10,0.07,0.0,0.01,0.18

Удаление колонки Rank

In [3]:
df = df.drop(columns='Rank')
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Let's Play Flight Attendant,DS,2010.0,Simulation,Deep Silver,0.02,0.00,0.0,0.00,0.02
1,Mini Ninjas,DS,2009.0,Action,Eidos Interactive,0.17,0.15,0.0,0.04,0.35
2,SingStar Pop Hits,PS2,2007.0,Misc,Sony Computer Entertainment,0.00,0.50,0.0,0.15,0.65
3,Super Army War,GBA,2005.0,Action,Flashpoint Games,0.03,0.01,0.0,0.00,0.04
4,Rocket Power: Zero Gravity Zone,GBA,2003.0,Sports,THQ,0.14,0.05,0.0,0.00,0.20
...,...,...,...,...,...,...,...,...,...,...
548,Ultimate NES Remix,3DS,2014.0,Action,Unknown,0.15,0.09,0.0,0.02,0.27
549,Jambo! Safari Animal Rescue,Wii,2009.0,Simulation,Sega,0.07,0.01,0.0,0.01,0.09
550,Tiger Woods PGA Tour 12: The Masters,PS3,2011.0,Sports,Electronic Arts,0.52,0.26,0.0,0.12,0.90
551,Elf: The Movie,GBA,2004.0,Action,Crave Entertainment,0.10,0.04,0.0,0.00,0.15
552,Fear Effect 2: Retro Helix,PS,2001.0,Action,Eidos Interactive,0.10,0.07,0.0,0.01,0.18

Удаление колонки Other_Sales

In [4]:
df = df.drop(columns='Other_Sales')
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,Let's Play Flight Attendant,DS,2010.0,Simulation,Deep Silver,0.02,0.00,0.0,0.02
1,Mini Ninjas,DS,2009.0,Action,Eidos Interactive,0.17,0.15,0.0,0.35
2,SingStar Pop Hits,PS2,2007.0,Misc,Sony Computer Entertainment,0.00,0.50,0.0,0.65
3,Super Army War,GBA,2005.0,Action,Flashpoint Games,0.03,0.01,0.0,0.04
4,Rocket Power: Zero Gravity Zone,GBA,2003.0,Sports,THQ,0.14,0.05,0.0,0.20
...,...,...,...,...,...,...,...,...,...
548,Ultimate NES Remix,3DS,2014.0,Action,Unknown,0.15,0.09,0.0,0.27
549,Jambo! Safari Animal Rescue,Wii,2009.0,Simulation,Sega,0.07,0.01,0.0,0.09
550,Tiger Woods PGA Tour 12: The Masters,PS3,2011.0,Sports,Electronic Arts,0.52,0.26,0.0,0.90
551,Elf: The Movie,GBA,2004.0,Action,Crave Entertainment,0.10,0.04,0.0,0.15
552,Fear Effect 2: Retro Helix,PS,2001.0,Action,Eidos Interactive,0.10,0.07,0.0,0.18

Использование OrdinalEncoder

In [5]:
from sklearn.preprocessing import OrdinalEncoder

Oenc = OrdinalEncoder()
Oenc.fit(df[['Name','Platform','Year','Genre']])
Oenc

OrdinalEncoder()

Вывод категорий OrdinalEncoder

In [6]:
Oenc.categories_

[array(['1/2 Summer +', '18 Wheeler: American Pro Trucker',
        '187: Ride or Die', '2 Games in 1: Sonic Advance & ChuChu Rocket!',
        '2002 FIFA World Cup', '7 Days to Die', 'Act of Aggression',
        'Adventure Time: The Secret of the Nameless',
        'Agatha Christie: And Then There Were None',
        'Air Conflicts: Aces of World War II', 'Alien Trilogy',
        'Are You Alice?', 'Army Corps of Hell', 'Army Men: Green Rogue',
        'Around the World in 80 Days', "Assassin's Creed: Brotherhood",
        'Assault', "Atari's Greatest Hits: Volume 1",
        'Atelier Annie: Alchemists of Sera Island',
        'Atelier Ayesha: The Alchemist of Dusk', 'Attack of the Movies 3D',
        'Avatar: The Game', 'Avatar: The Last Airbender',
        'Avatar: The Last Airbender - Into the Inferno',
        "Backyard NFL Football '09", 'Baku Baku', 'Band Hero',
        'Baten Kaitos: Eternal Wings and the Lost Ocean', 'Batman Begins',
        'Battle Rage', 'BattleTanx', 'Beat Down: Fists of Vengeance',
        'BeatMania IIDX 13: DistorteD', 'Bejeweled 3',
        'Ben 10 Alien Force: Vilgax Attacks',
        'Ben 10 Ultimate Alien: Cosmic Destruction', 'Big Mountain 2000',
        'BioShock 2', 'Black Dawn', 'Blackthorne',
        'Blade Arcus from Shining EX', 'Blast Corps',
        'Blazing Souls: Accelate',
        'Boku no Natsuyasumi Portable 2: Nazo Nazo Shimai to Chinbotsusen no Himitsu',
        'Bomberman Land', 'Botanicula',
        'Brain Age 2: More Training in Minutes a Day',
        "Brave: A Warrior's Tale", 'Breath of Fire: Dragon Quarter',
        'Brunswick Pro Bowling', 'Burnout Paradise: The Ultimate Box',
        'Busou Renkin: Youkoso Papillon Park e', 'Bust-A-Move DS',
        'Butt-Ugly Martians: Zoom or Doom!', 'C.O.R.E.',
        'CSI: Fatal Conspiracy', 'CSI: Unsolved!',
        "Cabela's Big Game Hunter (2008)", "Cabela's Trophy Bucks",
        'Call of Duty 3', 'Call of Duty: Black Ops',
        'Call of Duty: Modern Warfare Trilogy',
        'Cars: Mater-National Championship', 'Casper',
        'Castlevania: Circle of the Moon',
        'Castlevania: Lords of Shadow 2', 'Castrol Honda Superbike Racing',
        'Championship Pony', 'Chromehounds', 'Chrysler Classic Racing',
        "Clive Barker's Jericho", 'Code R',
        'Code:Realize - Sousei no Himegimi', 'Cold Fear',
        'Colin McRae Rally 2.0', 'Command & Conquer: Tiberian Sun',
        'Commandos: Strike Force',
        'Conception II: Children of the Seven Stars',
        'Condemned: Criminal Origins', 'Conflict: Denied Ops',
        'Cool Boarders 2001', 'Corpse Party: Blood Drive', 'Corvette',
        'Crash Bandicoot 2: N-Tranced', 'Crash: Mind Over Mutant',
        'Crayon Shin-Chan Shokkugan! Densetsu o Yobu Omake Daiketsusen!!',
        'Crayon Shin-chan: Arashi o Yobu Kasukabe Eiga Stars!',
        'Crazy Machines', 'Crazy Taxi', 'Culdcept Revolt',
        'DC Universe Online', 'DJ Hero', 'DX Game of Life', 'Dark Cloud',
        'Daytona USA Championship Circuit Edition',
        'Dead Rising 2: Off the Record', 'Dead or Alive', 'Dead to Rights',
        'Deadpool', 'Deal or No Deal', 'DeathSmiles',
        'Deception IV: Blood Ties', 'Def Jam: Fight for NY', 'Desire',
        'Deus Ex: Human Revolution', 'Digimon Racing', 'Digimon World 2',
        'Digimon World: Next Order', 'Discovery Kids: Puppy Playtime',
        'Disney Infinity 2.0: Marvel Super Heroes',
        'Disney Sing It! High School Musical 3: Senior Year',
        "Disney's Kim Possible 2: Drakken's Demise",
        "Disney's The Haunted Mansion", 'Donkey Kong Country 3',
        'Doodle Hex', 'Dragon Age: Origins - Ultimate Edition',
        'Dragon Quest Swords: The Masked Queen and the Tower of Mirrors',
        "Dragon's Dogma", 'DreamWorks Super Star Kartz',
        'Driving Emotion Type-S', 'Dying Light', 'Dynasty Warriors 4',
        'Dynasty Warriors Advance', 'EA Sports Active: More Workouts',
        'ESPN NBA 2K5', 'Element Hunter', 'Elf: The Movie',
        'Elminage II DS Remix: Sousei no Megami to Unmai no Daichi',
        'End of Nations', 'Eragon', 'Escape Dead Island', 'Eternal Eyes',
        'Etrian Odyssey II: Heroes of Lagaard',
        'Eureka Seven Vol. 2: The New Vision', 'Exstetra', 'F1 2001',
        'F1 2002', 'F1 Pole Position 64', 'FIFA Soccer 06',
        'FIFA Soccer 10', 'FIFA Soccer 2003', 'FIFA Street',
        'FIFA World Cup Germany 2006', 'FIFA: Road to  World Cup 98',
        'Fallout 3 Game Add-On Pack: Broken Steel and Point Lookout',
        'Fallout 3 Game Add-On Pack: The Pitt and Operation: Anchorage',
        'Fantastic Voyage', 'Far Cry 2', 'Farm Frenzy 3',
        'Fashion Studio: Paris Collection', 'Fatal Frame', 'Fatal Fury 2',
        'Fear Effect 2: Retro Helix', 'Final Approach 2: 1st Priority',
        'Final Fantasy X/X-2 HD Remaster', 'Fit in Six',
        'Forza Motorsport 4', 'Fullmetal Alchemist: Brotherhood',
        'Fuse (Insomniac)', 'Fuzion Frenzy', 'Galactic Attack',
        "Garfield's Fun Fest", 'Garfield: The Search for Pooky',
        'Gears of War', 'Genji: Days of the Blade', 'Gex',
        'Ghostbusters: The Video Game', 'Goat Simulator',
        'Godzilla Unleashed: Double Smash',
        'Godzilla: Destroy All Monsters Melee', 'Golden Sun: The Lost Age',
        'Grand Slam Tennis 2', 'Grand Theft Auto',
        'Grisaia no Kajitsu: La Fruit de la Grisaia',
        'Guitar Freaks V & DrumMania V', 'Guitar Hero 5',
        'Guitar Hero: World Tour', 'GunParade Orchestra: Midori no Shou',
        'Hanagumi Taisen Columns',
        'Haneru no Tobira DS: Tanshuku Tetsudou no Yoru', 'Hannah Montana',
        'Happy Feet Two', 'Harry Potter and the Goblet of Fire',
        'Harvest Moon: Magical Melody',
        'Hatsune Miku: Project Diva Extend',
        'Hatsune Miku: Project Diva X', 'Hatsune Miku: Project Diva f',
        'Hatsune Miku: Project Mirai 2', 'Hellboy: The Science of Evil',
        'Hello Kitty Seasons', 'High Heat Baseball 2002',
        'Hiiro no Kakera 3: Aoikuro no Kusabi',
        'Hisshou Pachinko*Pachi-Slot Kouryaku Series DS Vol. 2: Shinseiki Evangelion - Shito, Futatabi',
        'Homefront', 'Hot Wheels Ultimate Racing',
        "Hot Wheels: Burnin' Rubber", 'Hyperdimension Neptunia Re;Birth 2',
        'Hyperdimension Neptunia Vs. Sega Hard Girls: Yume no Gattai Special',
        'I Am In The Movie', 'I Heart Geeks', 'I Love Puppies',
        'Imagine: Wedding Designer',
        'International Superstar Soccer 2000 (All region sales)',
        'Inversion', 'Invizimals: The Alliance',
        'J-League Pro Soccer Club o Tsukurou!',
        'J-League Winning Eleven 2008: Club Championship',
        'Jambo! Safari Animal Rescue',
        'James Bond 007: Everything or Nothing', 'James Bond 007: Legends',
        'Jeopardy!', 'Jewel Quest IV: Heritage',
        'Jikkyou Powerful Pro Yakyuu 13',
        'Jikkyou Powerful Pro Yakyuu 13 Ketteiban',
        'Jikkyou Powerful Pro Yakyuu Portable 4',
        'Jimmy Neutron: Boy Genius', 'Jirou Akagawa: Majotachi no Nemuri',
        "John Daly's ProStroke Golf", "Jumper: Griffin's Story",
        'Just Dance 2', 'Just Dance 4', 'Just Dance: Disney Party 2',
        'Juusanshi Engi Engetsu Sangokuden 2', 'K-1 World Grand Prix',
        'Kaidan Restaurant: Zoku! Shin Menu 100-Sen', 'Kakuto Chojin',
        'Karaoke Revolution Party',
        'Katekyoo Hitman Reborn! DS: Ore ga Boss! Saikyou Family Taisen',
        'Killer is Dead', 'Kinect Adventures!', 'Kinect Star Wars',
        'Kingdom: Ikkitousen no Ken', 'Kiniro no Corda 2 f Encore',
        'Kintaihi Shounen no Jiken: Kyakusen Eris-Gou no Sangeki',
        'Konami Classics Series: Arcade Hits',
        'Kyokugen Dasshutsu ADV: Zennin Shiboudesu',
        'LEGO Marvel Super Heroes', 'LEGO Ninjago: Shadow of Ronin',
        'LEGO Pirates of the Caribbean: The Video Game',
        'LEGO Star Wars III: The Clone Wars', 'LEGO The Lord of the Rings',
        "Legend of the Guardians: The Owls of Ga'Hoole",
        'Lego Star Wars: The Force Awakens',
        "Lemony Snicket's A Series of Unfortunate Events",
        "Let's Play Ballerina", "Let's Play Flight Attendant", 'Lifeline',
        'Lizzie McGuire 2: Lizzie Diaries', 'Loons: The Fight For Fame',
        'Lords of the Fallen', 'Love Plus', 'Lucky Luke', 'Lunacy',
        'Lunar: Silver Star Harmony', 'Luxor: The Wrath of Set',
        'MLB 2K9 Fantasy All-Stars',
        'MX SuperFly featuring Ricky Carmichael',
        'MX vs. ATV Supercross Encore', 'MX vs. ATV Unleashed',
        'Mace Griffin: Bounty Hunter', 'Madden NFL 07', 'Madden NFL 08',
        'Madden NFL 11', 'Madden NFL 2002', 'Madden NFL 99',
        'Magna Carta 2', 'Mahjong Fight Club DS: Wi-Fi Taiou',
        'Major League Baseball 2K11', 'MapleStory DS',
        'Marriage Royale: Prism Story', 'Mass Effect 3',
        "Mat Hoffman's Pro BMX 2", 'Max Payne', 'Maximum Chase',
        'Meccha! Taiko no Tatsujin Master DS: 7-tsu no Shima no Daibouken',
        'MediEvil: Resurrection', 'Mega Man ZX',
        'Megamind: Ultimate Showdown', 'Metal Gear Ac!d 2',
        'Miami Vice: The Game', 'Michael Phelps: Push the Limit',
        'Minecraft', 'Mini Ninjas', 'Miracle Girls Festival',
        'Mobile Suit Gundam Side Story I: Senritsu no Blue',
        'Mobile Suit Gundam: Giren no Yabou Zeon Dokuritsu Sensouden',
        'Momotarou Dentetsu 15', 'Momotarou Dentetsu 16', 'Monopoly',
        'Monster Hunter Frontier Online',
        'Monster Hunter Frontier Online: Forward 2', 'Monster Jam',
        'MotoGP 07', 'Muv-Luv Alternative: Total Eclipse',
        'Myself; Yourself', 'Mystery Case Files: The Malgrave Incident',
        'NARC', 'NASCAR 2011: The Game', 'NBA 2K14', 'NBA 2K15',
        'NBA Live 97', 'NBA Street V3', 'NCAA March Madness 2004',
        'NFL Blitz 2001', 'NFL GameDay 2002', 'NHL 2002', 'NHL 2K7',
        'NHL 2K8', 'NHL Powerplay 98', 'NPPL: Championship Paintball 2009',
        'Namco Museum', 'Naughty Bear',
        'Nazotoki Battle Tore! Densetsu no Makyuu o Fukkatsu Saseyo!',
        'Need for Speed Underground', 'Need for Speed: Most Wanted',
        'NeoGeo Battle Coliseum', 'Nickelodeon Team Umizoomi',
        "No More Heroes: Heroes' Paradise", 'Nobunaga no Yabou DS',
        'Obscure: The Aftermath', 'Off-World Interceptor Extreme',
        'Onechanbara Special', 'Ontamarama', 'Over the Hedge',
        'PES 2009: Pro Evolution Soccer', 'Pachi-Slot Aruze Oukoku 3',
        'Pachitte Chonmage Tatsujin 13: Pachinko Hissatsu Shigotojin III',
        'Pacific Liberator', 'Painkiller',
        'Parfait: Chocolat Second Style', 'Pariah',
        'Penguins of Madagascar', 'Peppa Pig: The Game',
        'Percy Jackson and the Olympians: The Lightning Thief',
        "Peter Jackson's King Kong: The Official Game of the Movie",
        'Petz Rescue: Wildlife Vet', 'Phantasy Star Ø', 'Philosoma',
        'PilotWings Resort', 'Pipe Mania',
        'Plants vs. Zombies: Garden Warfare', 'Point Blank DS (JP sales)',
        'Pokemon Diamond/Pokemon Pearl',
        'Pokemon HeartGold/Pokemon SoulSilver', 'Polaris',
        "Pop'n TwinBee: Rainbow Bell Adventure", 'Power Pro Kun Pocket 14',
        'Power Pro Success Legends',
        'PriPara & Pretty Rhythm: PriPara de Tsukaeru Oshare Item 1450!',
        'Prince of Stride', 'Princess Debut',
        'Professor Layton and the Azran Legacy',
        'Pryzm Chapter One: The Dark Unicorn',
        'Psychedelica of the Black Butterfly', 'Puyo Puyo 7',
        'Radiant Silvergun', 'Rainbow Islands Revolution',
        'RalliSport Challenge', 'Ratchet & Clank: Size Matters',
        'Real Crimes: The Unicorn Killer', 'Red Faction',
        'Renai 0 Kilometer', 'Resident Evil', 'Risen 3: Titan Lords',
        'Robots', "Rock 'N Roll Racing", 'Rocket Power: Zero Gravity Zone',
        "Rockin' Pretty", 'Rocksmith',
        'Romance of the Three Kingdoms IV: Wall of Fire',
        'Rugby Challenge 3', 'Ryse: Son of Rome',
        'SD Gundam G Generation Spirits', 'SD Gundam: Gashapon Wars',
        'SafeCracker: The Ultimate Puzzle Adventure', 'Sailor Moon',
        'Saint Seiya: Sanctuary Battle', 'Saints Row',
        'Sakura Sakura: Haru Urara', 'Sammy Sosa High Heat Baseball 2001',
        'Samurai Jack: The Shadow of Aku', 'Samurai Shodown',
        'Samurai Shodown: Warrios Rage', 'Samurai Warriors 4-II',
        'Satisfashion', 'Scooby-Doo! Night of 100 Frights',
        'Scooby-Doo! and the Spooky Swamp',
        'Sega Ages 2500 Series Vol. 29: Monster World Complete Collection',
        'Sengoku Basara 4: Sumeragi',
        'Shin Megami Tensei: Devil Summoner 2 - Raidou Kuzunoha vs. King Abaddon (JP sales)',
        'Shin Nippon Pro Wrestling: Toukon Retsuden 2',
        'Shinobido 2: Tales of the Ninja',
        'Shinseiki Evangelion 2: Tsukurareshi Sekai - Another Cases',
        'Shippuu Mahou Daisakusen: Kingdom-Grandprix', 'Shrek Super Party',
        'Simple DS Series Vol. 14: The Jidousha Kyoushuujo DS',
        'Simple DS Series Vol. 8: The Kanshikikan - Kinkyuu Shutsudou!! Jiken Genba wo Touch Seyo',
        'SingStar Amped', 'SingStar Pop Hits', 'SingStar Take That',
        'SingStar: Made In Germany', 'Siren: Blood Curse',
        'Ski Region Simulator', 'Skydiving Extreme', 'Skylanders Giants',
        'Skylanders: SuperChargers', 'Skylanders: Trap Team', 'Slayers',
        'Sleeping Dogs', "Smuggler's Run", 'Sniper Elite',
        'Snood 2: On Vacation', 'Sonic Unleashed',
        'Spectral Souls: Resurrection of the Ethereal Empires',
        'Spider-Man 2', 'Spider-Man: Web of Shadows', 'SplashDown',
        'Squinkies 2: Adventure Mall Surprize!', 'Star Ocean: Blue Sphere',
        'Star Trek: Legacy', 'Star Wars: Dark Forces',
        'Starry ? Sky: After Spring', 'State of Decay',
        'Steel Battalion: Line of Contact', 'Storm Lover Kai!!',
        'Street Fighter Alpha 3 MAX', 'Street Hoops',
        'Strike Witches: Shirogane no Tsubasa', 'Stunt GP',
        'Summer Sports: Paradise Island', 'Super Army War',
        'Super Bowling', 'Super Famista 3', 'Super Fire ProWrestling',
        "Super Ghouls 'n Ghosts", 'Super Monkey Ball Adventure',
        'Super R.C. Pro-Am',
        'Super Robot Taisen OG Saga: Masou Kishin III - Pride of Justice',
        'Super Robot Wars OG: The Moon Dwellers', 'Superman Returns',
        'Superman: The Man of Steel', 'Syberia II',
        'TOCA Touring Car Championship', 'TV Total Events',
        'Tag Team Match M.U.S.C.L.E.',
        'Tales of the World: Radiant Mythology 3',
        'Tamagotchi Connection: Corner Shop 3', 'Tearaway Unfolded',
        'Teenage Mutant Ninja Turtles 2: Battle Nexus',
        'Tenchu 2: Birth of the Stealth Assassins',
        'Tenchu: Stealth Assassins', 'Tenjin Ranman: Happy GO Lucky!!',
        'Terraria', 'Test Drive: Ferrari Legends', 'Test Drive: Off Road',
        'The Adventures of Jimmy Neutron Boy Genius vs. Jimmy Negatron',
        "The Bard's Tale", 'The Croods: Prehistoric Party!',
        'The Elder Scrolls V: Skyrim',
        'The Idolmaster: Gravure For You! Vol. 2', 'The Incredible Hulk',
        'The Incredible Hulk: Ultimate Destruction',
        'The King of Fighters XII', 'The LEGO Movie Videogame',
        'The Last Airbender',
        'The Legend of Heroes: Trails in the Sky Second Chapter',
        'The Legend of Spyro: Dawn of the Dragon',
        'The Lord of the Rings: The Fellowship of the Ring',
        'The Mummy Returns', 'The Next BIG Thing',
        "The Peanuts Movie: Snoopy's Grand Adventure",
        'The Raiden Project', 'The Simpsons: Hit & Run',
        'The Sims 3: Ambitions', 'The Smurfs', 'The Smurfs 2',
        'Thrillville', 'Tiger Woods PGA Tour 12: The Masters',
        'Tiger Woods PGA Tour 2005', 'Time Commando', 'Time Travelers',
        'Timmy Time', 'Togainu no Chi: True Blood',
        "Tom Clancy's Ghost Recon Advanced Warfighter",
        "Tom Clancy's Splinter Cell: Conviction", 'Tomb Raider: Legend',
        "Tony Hawk's American Wasteland", 'Tony Hawk: RIDE',
        'Tony Hawk: Shred', 'Top Gun: Combat Zones',
        'Toriko: Gourmet Battle!', 'Tornado Outbreak', 'Total War: Attila',
        'Tour de France 2014', 'Transformer: Rise of the Dark Spark',
        'Trauma Center: New Blood', 'Travel Coach: Europe 1',
        'Triple Crown Championship Snowboarding', 'Tron 2.0: Killer App',
        'Tropico 4', 'True Crime: Streets of LA',
        'Ty the Tasmanian Tiger 3: Night of the Quinkan', 'U-Sing',
        'UFC Undisputed 3', "Ultimate Ghosts 'n Goblins (JP sales)",
        'Ultimate NES Remix', 'Ultimate Puzzle Games', 'Unreal Anthology',
        'V-Rally 3', 'Vantage Master Portable',
        'Violet no Atelier: Gramnad no Renkinjutsushi 2 - Gunjou no Omoide',
        'Virtua Quest', 'Virtua Tennis 3', 'Virtual Chess 64',
        'WCW vs the World', 'WTA Tour Tennis', 'WWE 2K14',
        'WWE SmackDown vs. Raw 2010', 'WWF Raw',
        'Wallace & Gromit: Curse of the Were-Rabbit',
        'Wario Land II (GBC)', 'Warriors: Legends of Troy',
        'We Sing Deutsche Hits', 'Wetrix',
        'Winning Eleven: Pro Evolution Soccer 2007 (All Region sales)',
        'Wipeout: The Game', 'Wizardry Twin Pack',
        'World Snooker Challenge 2005',
        'World in Conflict: Complete Edition', 'X-Men Legends',
        'X-Men: Destiny', 'XGIII: Extreme G Racing', 'Yakuza 5',
        'Yattaman DS: BikkuriDokkiri Daisakusen da Koron', 'Yoga Wii',
        'Yokai Watch 2 Shinuchi', 'Yu-Gi-Oh! Reshef of Destruction',
        'Zatch Bell! Mamodo Fury', 'Zen-Nippon GT Senshuken',
        'Zoo Tycoon 2 DS'], dtype=object),
 array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'N64', 'NES', 'PC',
        'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES', 'Wii',
        'WiiU', 'X360', 'XB', 'XOne'], dtype=object),
 array([1981., 1982., 1985., 1991., 1993., 1994., 1995., 1996., 1997.,
        1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005., 2006.,
        2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014., 2015.,
        2016.,   nan]),
 array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
        'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
        'Strategy'], dtype=object)]

Использование OrdinalEncoder

In [7]:
from sklearn.preprocessing import OrdinalEncoder

Oenc = OrdinalEncoder()
df[['Name','Platform','Year','Genre']] = Oenc.fit_transform(df[['Name','Platform','Year','Genre']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,0.02,0.00,0.0,0.02
1,282.0,3.0,20.0,0.0,Eidos Interactive,0.17,0.15,0.0,0.35
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.00,0.50,0.0,0.65
3,430.0,5.0,16.0,0.0,Flashpoint Games,0.03,0.01,0.0,0.04
4,366.0,5.0,14.0,10.0,THQ,0.14,0.05,0.0,0.20
...,...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,0.15,0.09,0.0,0.27
549,207.0,18.0,20.0,9.0,Sega,0.07,0.01,0.0,0.09
550,477.0,12.0,22.0,10.0,Electronic Arts,0.52,0.26,0.0,0.90
551,126.0,5.0,15.0,0.0,Crave Entertainment,0.10,0.04,0.0,0.15
552,152.0,10.0,12.0,0.0,Eidos Interactive,0.10,0.07,0.0,0.18

Использование LabelEncoder

In [8]:
from sklearn.preprocessing import LabelEncoder

Lenc = LabelEncoder()
Lenc.fit(df['Global_Sales'])
df['Global_Sales'] = Lenc.fit_transform(df['Global_Sales'])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,0.02,0.00,0.0,1
1,282.0,3.0,20.0,0.0,Eidos Interactive,0.17,0.15,0.0,34
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.00,0.50,0.0,62
3,430.0,5.0,16.0,0.0,Flashpoint Games,0.03,0.01,0.0,3
4,366.0,5.0,14.0,10.0,THQ,0.14,0.05,0.0,19
...,...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,0.15,0.09,0.0,26
549,207.0,18.0,20.0,9.0,Sega,0.07,0.01,0.0,8
550,477.0,12.0,22.0,10.0,Electronic Arts,0.52,0.26,0.0,76
551,126.0,5.0,15.0,0.0,Crave Entertainment,0.10,0.04,0.0,14
552,152.0,10.0,12.0,0.0,Eidos Interactive,0.10,0.07,0.0,17

Вывод классов LabelEncoder

In [9]:
Lenc.classes_

array([1.000e-02, 2.000e-02, 3.000e-02, 4.000e-02, 5.000e-02, 6.000e-02,
       7.000e-02, 8.000e-02, 9.000e-02, 1.000e-01, 1.100e-01, 1.200e-01,
       1.300e-01, 1.400e-01, 1.500e-01, 1.600e-01, 1.700e-01, 1.800e-01,
       1.900e-01, 2.000e-01, 2.100e-01, 2.200e-01, 2.300e-01, 2.400e-01,
       2.500e-01, 2.600e-01, 2.700e-01, 2.800e-01, 2.900e-01, 3.000e-01,
       3.100e-01, 3.200e-01, 3.300e-01, 3.400e-01, 3.500e-01, 3.600e-01,
       3.800e-01, 3.900e-01, 4.000e-01, 4.100e-01, 4.200e-01, 4.300e-01,
       4.400e-01, 4.500e-01, 4.600e-01, 4.700e-01, 4.800e-01, 4.900e-01,
       5.000e-01, 5.100e-01, 5.200e-01, 5.300e-01, 5.400e-01, 5.500e-01,
       5.600e-01, 5.700e-01, 5.800e-01, 5.900e-01, 6.000e-01, 6.200e-01,
       6.300e-01, 6.400e-01, 6.500e-01, 6.600e-01, 6.800e-01, 7.100e-01,
       7.600e-01, 7.700e-01, 7.800e-01, 8.100e-01, 8.200e-01, 8.300e-01,
       8.400e-01, 8.700e-01, 8.800e-01, 8.900e-01, 9.000e-01, 9.100e-01,
       9.200e-01, 9.500e-01, 9.600e-01, 9.700e-01, 1.000e+00, 1.030e+00,
       1.040e+00, 1.050e+00, 1.120e+00, 1.140e+00, 1.160e+00, 1.190e+00,
       1.210e+00, 1.220e+00, 1.280e+00, 1.290e+00, 1.360e+00, 1.380e+00,
       1.390e+00, 1.400e+00, 1.460e+00, 1.520e+00, 1.540e+00, 1.550e+00,
       1.560e+00, 1.580e+00, 1.640e+00, 1.710e+00, 1.740e+00, 1.780e+00,
       1.800e+00, 1.830e+00, 1.920e+00, 1.930e+00, 1.990e+00, 2.060e+00,
       2.090e+00, 2.100e+00, 2.110e+00, 2.190e+00, 2.210e+00, 2.280e+00,
       2.380e+00, 2.470e+00, 2.650e+00, 2.680e+00, 2.840e+00, 3.770e+00,
       4.020e+00, 4.210e+00, 4.240e+00, 4.640e+00, 4.700e+00, 5.050e+00,
       6.110e+00, 6.560e+00, 9.520e+00, 1.190e+01, 1.464e+01, 1.530e+01,
       1.836e+01, 2.182e+01])

Использование OneHotEncoder

In [10]:
from sklearn.preprocessing import OrdinalEncoder

Onhot = OrdinalEncoder()
Onhot.fit(df[['NA_Sales','EU_Sales','JP_Sales','Global_Sales']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,0.02,0.00,0.0,1
1,282.0,3.0,20.0,0.0,Eidos Interactive,0.17,0.15,0.0,34
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.00,0.50,0.0,62
3,430.0,5.0,16.0,0.0,Flashpoint Games,0.03,0.01,0.0,3
4,366.0,5.0,14.0,10.0,THQ,0.14,0.05,0.0,19
...,...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,0.15,0.09,0.0,26
549,207.0,18.0,20.0,9.0,Sega,0.07,0.01,0.0,8
550,477.0,12.0,22.0,10.0,Electronic Arts,0.52,0.26,0.0,76
551,126.0,5.0,15.0,0.0,Crave Entertainment,0.10,0.04,0.0,14
552,152.0,10.0,12.0,0.0,Eidos Interactive,0.10,0.07,0.0,17

Вывод категорий OneHotEncoder

In [11]:
Onhot.categories_

[array([0.000e+00, 1.000e-02, 2.000e-02, 3.000e-02, 4.000e-02, 5.000e-02,
        6.000e-02, 7.000e-02, 8.000e-02, 9.000e-02, 1.000e-01, 1.100e-01,
        1.200e-01, 1.300e-01, 1.400e-01, 1.500e-01, 1.600e-01, 1.700e-01,
        1.800e-01, 1.900e-01, 2.000e-01, 2.100e-01, 2.200e-01, 2.300e-01,
        2.400e-01, 2.500e-01, 2.600e-01, 2.700e-01, 2.800e-01, 2.900e-01,
        3.000e-01, 3.100e-01, 3.200e-01, 3.300e-01, 3.500e-01, 3.600e-01,
        3.800e-01, 3.900e-01, 4.000e-01, 4.100e-01, 4.200e-01, 4.300e-01,
        4.500e-01, 4.600e-01, 4.700e-01, 4.900e-01, 5.000e-01, 5.200e-01,
        5.500e-01, 5.600e-01, 5.800e-01, 5.900e-01, 6.000e-01, 6.100e-01,
        6.200e-01, 6.300e-01, 6.500e-01, 7.200e-01, 7.600e-01, 7.700e-01,
        7.800e-01, 8.200e-01, 8.300e-01, 8.400e-01, 8.800e-01, 9.300e-01,
        9.400e-01, 9.500e-01, 9.600e-01, 9.800e-01, 1.000e+00, 1.050e+00,
        1.090e+00, 1.150e+00, 1.170e+00, 1.200e+00, 1.310e+00, 1.380e+00,
        1.400e+00, 1.450e+00, 1.460e+00, 1.550e+00, 1.590e+00, 1.660e+00,
        1.730e+00, 1.870e+00, 1.970e+00, 2.040e+00, 2.050e+00, 2.080e+00,
        2.100e+00, 2.550e+00, 3.000e+00, 3.440e+00, 3.540e+00, 4.400e+00,
        5.840e+00, 6.420e+00, 9.670e+00, 1.497e+01]),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
        0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.44,
        0.46, 0.48, 0.49, 0.5 , 0.54, 0.55, 0.57, 0.59, 0.6 , 0.63, 0.64,
        0.66, 0.7 , 0.72, 0.78, 0.8 , 0.82, 0.9 , 0.92, 0.96, 1.11, 1.16,
        1.34, 1.4 , 1.87, 1.9 , 2.  , 2.04, 2.19, 2.55, 2.71, 2.77, 2.89,
        3.73, 4.52, 4.94, 5.36]),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.24, 0.25, 0.26, 0.27, 0.28, 0.31, 0.33, 0.35, 0.36, 0.38,
        0.39, 0.4 , 0.45, 0.5 , 0.53, 0.59, 0.65, 0.72, 1.05, 1.11, 2.68,
        3.96, 5.32, 6.04]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139], dtype=int64)]

Перевод столбца у OneHotEncoder в массив

In [12]:
Onhot.transform(df[['NA_Sales','EU_Sales','JP_Sales','Global_Sales']])

array([[ 2.,  0.,  0.,  1.],
       [17., 15.,  0., 34.],
       [ 0., 47.,  0., 62.],
       ...,
       [47., 26.,  0., 76.],
       [10.,  4.,  0., 14.],
       [10.,  7.,  0., 17.]])

Вывод

In [13]:
df[['NA_Sales','EU_Sales','JP_Sales','Global_Sales']] = Onhot.fit_transform(df[['NA_Sales','EU_Sales','JP_Sales','Global_Sales']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,2.0,0.0,0.0,1.0
1,282.0,3.0,20.0,0.0,Eidos Interactive,17.0,15.0,0.0,34.0
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.0,47.0,0.0,62.0
3,430.0,5.0,16.0,0.0,Flashpoint Games,3.0,1.0,0.0,3.0
4,366.0,5.0,14.0,10.0,THQ,14.0,5.0,0.0,19.0
...,...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,15.0,9.0,0.0,26.0
549,207.0,18.0,20.0,9.0,Sega,7.0,1.0,0.0,8.0
550,477.0,12.0,22.0,10.0,Electronic Arts,47.0,26.0,0.0,76.0
551,126.0,5.0,15.0,0.0,Crave Entertainment,10.0,4.0,0.0,14.0
552,152.0,10.0,12.0,0.0,Eidos Interactive,10.0,7.0,0.0,17.0

Удаление столбца RainToday

In [14]:
df = df.drop(columns='Global_Sales')
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,2.0,0.0,0.0
1,282.0,3.0,20.0,0.0,Eidos Interactive,17.0,15.0,0.0
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.0,47.0,0.0
3,430.0,5.0,16.0,0.0,Flashpoint Games,3.0,1.0,0.0
4,366.0,5.0,14.0,10.0,THQ,14.0,5.0,0.0
...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,15.0,9.0,0.0
549,207.0,18.0,20.0,9.0,Sega,7.0,1.0,0.0
550,477.0,12.0,22.0,10.0,Electronic Arts,47.0,26.0,0.0
551,126.0,5.0,15.0,0.0,Crave Entertainment,10.0,4.0,0.0
552,152.0,10.0,12.0,0.0,Eidos Interactive,10.0,7.0,0.0

Использование Normalizer

In [15]:
from sklearn.preprocessing import Normalizer

Norm = Normalizer()
df[['NA_Sales','EU_Sales']] = Norm.fit_transform(df[['NA_Sales','EU_Sales']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales
0,245.0,3.0,21.0,9.0,Deep Silver,1.000000,0.000000,0.0
1,282.0,3.0,20.0,0.0,Eidos Interactive,0.749838,0.661622,0.0
2,398.0,11.0,18.0,3.0,Sony Computer Entertainment,0.000000,1.000000,0.0
3,430.0,5.0,16.0,0.0,Flashpoint Games,0.948683,0.316228,0.0
4,366.0,5.0,14.0,10.0,THQ,0.941742,0.336336,0.0
...,...,...,...,...,...,...,...,...
548,505.0,1.0,25.0,0.0,Unknown,0.857493,0.514496,0.0
549,207.0,18.0,20.0,9.0,Sega,0.989949,0.141421,0.0
550,477.0,12.0,22.0,10.0,Electronic Arts,0.875034,0.484061,0.0
551,126.0,5.0,15.0,0.0,Crave Entertainment,0.928477,0.371391,0.0
552,152.0,10.0,12.0,0.0,Eidos Interactive,0.819232,0.573462,0.0

Использование train_test_split

In [16]:
from sklearn.model_selection import train_test_split

Y = df['Genre']
X = df.drop(columns=['Genre'])

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)
x_train

,Name,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales
18,341.0,3.0,17.0,Atari,0.000000,0.000000,7.0
325,267.0,14.0,22.0,Take-Two Interactive,1.000000,0.000000,0.0
486,538.0,17.0,6.0,Banpresto,0.000000,0.000000,4.0
296,106.0,10.0,11.0,Namco Bandai Games,0.820905,0.571064,16.0
478,457.0,18.0,24.0,D3Publisher,0.393919,0.919145,0.0
...,...,...,...,...,...,...,...
71,76.0,11.0,17.0,Eidos Interactive,0.832050,0.554700,0.0
106,168.0,3.0,18.0,Atari,1.000000,0.000000,0.0
270,139.0,9.0,20.0,Electronic Arts,0.000000,1.000000,0.0
435,527.0,14.0,16.0,Sega,0.000000,1.000000,0.0
102,81.0,15.0,25.0,Marvelous Interactive,0.964764,0.263117,6.0

In [17]:
y_test

548     0.0
82      0.0
523    10.0
332     3.0
132     1.0
       ...
140     8.0
149     3.0
498     0.0
153     8.0
172    11.0
Name: Genre, Length: 111, dtype: float64

In [18]:
x_test

,Name,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales
548,505.0,1.0,25.0,Unknown,0.857493,0.514496,0.0
82,405.0,22.0,26.0,Activision,0.954480,0.298275,0.0
523,212.0,11.0,17.0,Konami Digital Entertainment,0.000000,0.000000,30.0
332,457.0,18.0,24.0,D3Publisher,0.393919,0.919145,0.0
132,63.0,10.0,7.0,Interplay,0.811176,0.584802,0.0
...,...,...,...,...,...,...,...
140,61.0,20.0,27.0,Activision,0.707107,0.707107,0.0
149,525.0,18.0,20.0,Mindscape,1.000000,0.000000,0.0
498,388.0,12.0,26.0,Capcom,0.000000,0.000000,9.0
153,97.0,6.0,13.0,Electronic Arts,0.964764,0.263117,0.0
172,285.0,11.0,13.0,Namco Bandai Games,0.000000,0.000000,32.0